---
version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get -y install percona-toolkit mysql-client && pip3 install --upgrade awscli

  build:
    commands:
      - python3 --version
      - pt-online-schema-change --version
      - mysql --version
      - echo $PRIVATE_ACCESS_TOKEN
      - echo $COMMIT_ID
