---
version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get -y install percona-toolkit mysql-client && pip3 install --upgrade awscli

  build:
    commands:
      - echo $PRIVATE_ACCESS_TOKEN
      - echo $COMMIT_ID
      - mysql -h mysql-master.custom-db.com -u tester -e "show databases;"
